// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Message struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type NewMessage struct {
	Text string `json:"text"`
}
