version: "3.1"

services:
    db:
        image: mysql:5.6
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "app_user"
            MYSQL_PASSWORD: "password"
            MYSQL_DATABASE: message_app

    dockerhost:
        image: qoomon/docker-host:2.3.0
        cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
