/*
 * Messaging API
 *
 * Manage Messages
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type CreateMessageResponse struct {

	Id string `json:"id"`
}
