// Code generated by protoc-gen-kit. DO NOT EDIT.

package messagingv1

import (
	"context"
	kitgrpc "github.com/go-kit/kit/transport/grpc"
)

type MessageListKitServer struct {
	*UnimplementedMessageListServer

	CreateMessageHandler kitgrpc.Handler
	ListMessagesHandler  kitgrpc.Handler
	GetMessageHandler    kitgrpc.Handler
}

func (s MessageListKitServer) CreateMessage(ctx context.Context, req *CreateMessageRequest) (*CreateMessageResponse, error) {
	_, resp, err := s.CreateMessageHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*CreateMessageResponse), nil
}
func (s MessageListKitServer) ListMessages(ctx context.Context, req *ListMessagesRequest) (*ListMessagesResponse, error) {
	_, resp, err := s.ListMessagesHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*ListMessagesResponse), nil
}
func (s MessageListKitServer) GetMessage(ctx context.Context, req *GetMessageRequest) (*GetMessageResponse, error) {
	_, resp, err := s.GetMessageHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*GetMessageResponse), nil
}
