// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messaging/v1/message.proto

package messagingv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message is a note describing a message.
type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9eb19740eea0bf, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "messaging.v1.Message")
}

func init() {
	proto.RegisterFile("messaging/v1/message.proto", fileDescriptor_5d9eb19740eea0bf)
}

var fileDescriptor_5d9eb19740eea0bf = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xca, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0xcf, 0xcc, 0x4b, 0xd7, 0x2f, 0x33, 0xd4, 0x87, 0x70, 0x52, 0xf5, 0x0a, 0x8a, 0xf2,
	0x4b, 0xf2, 0x85, 0x78, 0xe0, 0x72, 0x7a, 0x65, 0x86, 0x4a, 0xba, 0x5c, 0xec, 0xbe, 0x10, 0x69,
	0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14,
	0x21, 0x21, 0x2e, 0x96, 0x92, 0xd4, 0x8a, 0x12, 0x09, 0x26, 0xb0, 0x08, 0x98, 0xed, 0x14, 0xca,
	0x25, 0x90, 0x9c, 0x9f, 0xab, 0x87, 0x6c, 0x84, 0x13, 0x9f, 0x2f, 0x8c, 0x17, 0x00, 0xb2, 0x20,
	0x80, 0x31, 0x8a, 0x1b, 0x2e, 0x5f, 0x66, 0xb8, 0x88, 0x89, 0x39, 0x24, 0x22, 0x62, 0x15, 0x13,
	0x0f, 0x5c, 0x95, 0x5e, 0x98, 0xe1, 0x29, 0x24, 0x6e, 0x4c, 0x98, 0x61, 0x12, 0x1b, 0xd8, 0x69,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0xfe, 0xfb, 0xa8, 0xb8, 0x00, 0x00, 0x00,
}
