// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
